### ISSUE TITLE
Doesn't look right on latest Spotify 1.2.53

### ISSUE THREAD

**Issue by MS-64** [sanoojes/spicetify-extensions#11]
![{D4C3FE2C-9D78-4471-9007-F1A40F0525AA}](https://github.com/user-attachments/assets/a74352fc-19c5-4ca4-a7aa-32bfcc7fc994)
![{24020DA1-2025-4511-9E54-88F6F24A835F}](https://github.com/user-attachments/assets/97f8a42d-201b-416b-9103-51e9fb573077)
Looks like the latest Spotify version broke how its supposed to look. I have reinstalled the extension but its the same.

Spotify for Windows (64 bit)
1.2.53.437.gd3a938d4
Spicetify v2.38.6

**Comment by sanoojes** [comment]
yes am fixing it rn
