### ISSUE TITLE
Libx has the problem with Dribbblish

### ISSUE THREAD

**Issue by ChrisVineyard-abc** [sanoojes/spicetify-extensions#5]
Libx is not compatible with Dribbblish, which causes navtar issues

**Comment by sanoojes** [comment]
Yes, I saw that issue on Discord. I've just fixed it now after working on a solution.

**Comment by sanoojes** [comment]
It looks like this right now 

![image](https://github.com/user-attachments/assets/04ee8fb0-9103-451d-a447-4ee619890742)

if you need to match the nav and library color add this snippet

```.Root__globalNav {background-color: var(--spice-sidebar) !important;}```

**Comment by ChrisVineyard-abc** [comment]
how can I update Libx? or it will autoupdate when i open spotify?

**Comment by ChrisVineyard-abc** [comment]
btw, i just updated Libx manually. Thank you so much!

**Comment by sanoojes** [comment]
> how can I update Libx? or it will autoupdate when i open spotify?

If you download the remote one it will update automatically else you have to follow the installation steps with the new js file
