### ISSUE TITLE
The top bar doesn't work

### ISSUE THREAD

**Issue by tai141** [sanoojes/spicetify-extensions#7]
![Capture](https://github.com/user-attachments/assets/ad9a8826-405b-45e3-b03b-d445922120f5)

So... my top bar doesn't work and none of the buttons are clickable beside the search button which is also completely broken.

**Comment by sanoojes** [comment]
sorry to hear that which theme are you in?

**Comment by sanoojes** [comment]
can you also give your `about spotify` ?

**Comment by tai141** [comment]
> sorry to hear that which theme are you in?

oh sharkblue or comfy I use both both are broken

**Comment by tai141** [comment]
> can you also give your `about spotify` ?

how do I see that?

**Comment by sanoojes** [comment]
like this 

![image](https://github.com/user-attachments/assets/b7d1e927-b0e4-4dc0-b369-d8e0c4a70a04)

**Comment by sanoojes** [comment]
i will check out older version i think its not supported in some of them

**Comment by sanoojes** [comment]
there was a issue on older versions i fixed it !
