### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by pcc404** [sanoojes/spicetify-extensions#9]
spotify jsut updated, im using the automatic updates version, the spotify view is tiny and most of the screen is just gray. Also, the top bar disappeared before the update (dunno if sitll as spotify is disfunctional rn) whenever not on the home screen. please fix these when you can ^^

**Comment by AylenSK** [comment]
That happened to me too. The extension stopped working. Tried to reinstall the extension manually, but no luck. 
BTW, I disabled Spotify auto-updates, so I don't know why this happened

**Comment by sanoojes** [comment]
It will be fixed soon it is caused because of my domain

**Comment by AylenSK** [comment]
Great! Thanks, @sanoojes :)

**Comment by sanoojes** [comment]
am changing the links to jsr cdn which will improve uptime

**Comment by sanoojes** [comment]
please reinstall your extension !

**Comment by AylenSK** [comment]
Now it works! :) Thank you so much, @sanoojes ❤️❤️ The new UI sucks
